import i18n, { t } from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

const resources = {
  en: {
    translation: {
      welcome: "Welcome",
      welcomeWithUser: "Welcome to our Blog App {{user}}",
      whatBrings: "What brings you to our blog app today?",
      createBlog: "Create a Blog",
      createBlogDesc: "Share your story with a modern interface.",
      title: "Title",
      category: "Category",
      image: "Image",
      content: "Content",
      postBlog: "Post Blog",
      livePreview: "Live Preview",
      yourTitle: "Your Title",
      yourContent: "Your content...",
      popularPosts: "Popular Posts",
      readMore: "Read More",
      by: "by",
      home: "Home",
      categories: "Categories",
      about: "About",
      help: "Help",
      signedInAs: "Signed in as",
      language: "Language",
      myProfile: "My Profile",
      myPosts: "My Posts",
      signOut: "Sign Out",
      noImage: "No image",
      writeYourContentHere: "Write your content here...",
      enterblogtitle: "Enter blog title",
      trendingNow: "Trending Now",
      // categories
      "category.sports": "Sports",
      "category.e-sports": "Esports",
      "category.cricket": "Cricket",
      "category.entertainment": "Entertainment",
      "category.others": "Others",
      pleaseEnterContentFirst: "Please enter some content first!",
      aiTitleIdeas: "✨ AI Title Ideas",
      aiGenerating: "✨ Generating...",
      aiPolish: "✨ AI Polish",
      aiImproving: "✨ Improving...",
      contentUpdated: "Content updated!",
      suggestedTitles: "Suggested Titles",
      clear: "Clear",
      apply: "Apply",
    },
  },
  ur: {
    translation: {
      welcome: "خوش آمدید",
      welcomeWithUser: "ہمارے بلاگ ایپ میں خوش آمدید {{user}}",
      whatBrings: "آج آپ ہمارے بلاگ ایپ پر کیوں آئے ہیں؟",
      createBlog: "بلاگ بنائیں",
      createBlogDesc: "اپنی کہانی جدید انٹرفیس کے ساتھ شیئر کریں۔",
      title: "عنوان",
      category: "زمرہ",
      image: "تصویر",
      content: "مشمول",
      postBlog: "بلاگ پوسٹ کریں",
      livePreview: "لائیو پری ویو",
      yourTitle: "آپ کا عنوان",
      yourContent: "آپ کا مواد...",
      popularPosts: "مقبول پوسٹس",
      readMore: "مزید پڑھیں",
      by: "بذریعہ",
      home: "ہوم",
      categories: "زمرے",
      about: "ہماری بارے میں",
      help: "مدد",
      signedInAs: "داخل شدہ صارف",
      language: "زبان",
      myProfile: "میری پروفائل",
      myPosts: "میری پوسٹس",
      signOut: "لاگ آؤٹ",
      noImage: "کوئی تصویر نہیں",
      writeYourContentHere: "اپنا مواد یہاں لکھیں...",
      enterblogtitle: "بلاگ کا عنوان درج کریں",
      trendingNow: "ابھی ٹرینڈ کر رہا ہے",
      // categories
      "category.sports": "کھیل",
      "category.e-sports": "ای-اسپورٹس",
      "category.cricket": "کرکٹ",
      "category.entertainment": "تفریح",
      "category.others": "دیگر",
      pleaseEnterContentFirst: "براہ کرم پہلے کچھ مواد درج کریں!",
      aiTitleIdeas: "✨ AI عنوان کے خیالات",
      aiGenerating: "✨ تیار ہو رہا ہے...",
      aiPolish: "✨ AI پالش",
      aiImproving: "✨ بہتری آ رہی ہے...",
      contentUpdated: "مواد اپ ڈیٹ ہو گیا!",
      suggestedTitles: "تجویز کردہ عنوانات",
      clear: "صاف کریں",
      apply: "لاگو کریں",
    },
  },
  ar: {
    translation: {
      welcome: "مرحبا",
      welcomeWithUser: "مرحبًا بك في تطبيق المدونة لدينا {{user}}",
      whatBrings: "ما الذي أتى بك إلى تطبيق المدونة الخاص بنا اليوم؟",
      createBlog: "إنشاء مدوّنة",
      createBlogDesc: "شارك قصتك بواجهة حديثة.",
      title: "العنوان",
      category: "الفئة",
      image: "صورة",
      content: "المحتوى",
      postBlog: "نشر المدوّنة",
      livePreview: "المعاينة الحية",
      yourTitle: "عنوانك",
      yourContent: "محتواك...",
      popularPosts: "المشاركات الشائعة",
      readMore: "اقرأ المزيد",
      by: "بواسطة",
      home: "الرئيسية",
      categories: "الفئات",
      about: "حول",
      help: "مساعدة",
      signedInAs: "مسجّل الدخول باسم",
      language: "اللغة",
      myProfile: "ملفي الشخصي",
      myPosts: "منشوراتي",
      signOut: "تسجيل الخروج",
      noImage: "لا توجد صورة",
      writeYourContentHere: "اكتب محتواك هنا...",
      enterblogtitle: "أدخل عنوان المدونة",
      trendingNow: "الرائج الآن",
      // categories
      "category.sports": "رياضة",
      "category.e-sports": "الرياضات الإلكترونية",
      "category.cricket": "الكريكيت",
      "category.entertainment": "ترفيه",
      "category.others": "أخرى",
      pleaseEnterContentFirst: "يرجى إدخال بعض المحتوى أولاً!",
      aiTitleIdeas: "✨ أفكار عناوين AI",
      aiGenerating: "✨ جاري التوليد...",
      aiPolish: "✨ تحسين AI",
      aiImproving: "✨ جاري التحسين...",
      contentUpdated: "تم تحديث المحتوى!",
      suggestedTitles: "العناوين المقترحة",
      clear: "مسح",
      apply: "تطبيق",
    },
  },
  hi: {
    translation: {
      welcome: "स्वागत है",
      welcomeWithUser: "हमारे ब्लॉग ऐप में आपका स्वागत है {{user}}",
      whatBrings: "आज आप हमारे ब्लॉग ऐप पर क्या लेकर आए हैं?",
      createBlog: "एक ब्लॉग बनाएं",
      createBlogDesc: "आधुनिक इंटरफ़ेस के साथ अपनी कहानी साझा करें।",
      title: "शीर्षक",
      category: "श्रेणी",
      image: "छवि",
      content: "सामग्री",
      postBlog: "ब्लॉग पोस्ट करें",
      livePreview: "लाइव पूर्वावलोकन",
      yourTitle: "आपका शीर्षक",
      yourContent: "आपकी सामग्री...",
      popularPosts: "लोकप्रिय पोस्ट",
      readMore: "और पढ़ें",
      by: "द्वारा",
      home: "होम",
      categories: "श्रेणियाँ",
      about: "हमारे बारे में",
      help: "मदद",
      signedInAs: "के रूप में साइन इन",
      language: "भाषा",
      myProfile: "मेरी प्रोफ़ाइल",
      myPosts: "मेरी पोस्ट",
      signOut: "साइन आउट",
      noImage: "कोई छवि नहीं",
      writeYourContentHere: "अपनी सामग्री यहां लिखें...",
      enterblogtitle: "ब्लॉग शीर्षक दर्ज करें",
      trendingNow: "अब ट्रेंडिंग",
      // categories
      "category.sports": "खेल",
      "category.e-sports": "ई-स्पोर्ट्स",
      "category.cricket": "क्रिकेट",
      "category.entertainment": "मनोरंजन",
      "category.others": "अन्य",
      pleaseEnterContentFirst: "कृपया पहले कुछ सामग्री दर्ज करें!",
      aiTitleIdeas: "✨ AI शीर्षक विचार",
      aiGenerating: "✨ तैयार हो रहा है...",
      aiPolish: "✨ AI पॉलिश",
      aiImproving: "✨ सुधार हो रहा है...",
      contentUpdated: "सामग्री अपडेट हो गई!",
      suggestedTitles: "सुझाए गए शीर्षक",
      clear: "साफ़ करें",
      apply: "लागू करें",
    },
  },
  zh: {
    translation: {
      welcome: "欢迎",
      welcomeWithUser: "欢迎来到我们的博客应用 {{user}}",
      whatBrings: "今天是什么把你带到我们的博客应用？",
      createBlog: "创建博客",
      createBlogDesc: "使用现代界面分享你的故事。",
      title: "标题",
      category: "类别",
      image: "图片",
      content: "内容",
      postBlog: "发布博客",
      livePreview: "实时预览",
      yourTitle: "你的标题",
      yourContent: "你的内容...",
      popularPosts: "热门文章",
      readMore: "阅读全文",
      by: "作者",
      home: "首页",
      categories: "分类",
      about: "关于",
      help: "帮助",
      signedInAs: "已登录为",
      language: "语言",
      myProfile: "我的资料",
      myPosts: "我的文章",
      signOut: "登出",
      noImage: "无图片",
      writeYourContentHere: "在这里写下你的内容...",
      enterblogtitle: "输入博客标题",
      trendingNow: "正在流行",
      // categories
      "category.sports": "体育",
      "category.e-sports": "电子竞技",
      "category.cricket": "板球",
      "category.entertainment": "娱乐",
      "category.others": "其他",
      pleaseEnterContentFirst: "请先输入一些内容！",
      aiTitleIdeas: "✨ AI 标题创意",
      aiGenerating: "✨ 正在生成...",
      aiPolish: "✨ AI 润色",
      aiImproving: "✨ 正在改进...",
      contentUpdated: "内容已更新！",
      suggestedTitles: "建议标题",
      clear: "清除",
      apply: "应用",
    },
  },
};

i18n
  .use(LanguageDetector) // detects browser/localStorage language
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    debug: false,
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
