# Generated by Django 6.0.3 on 2026-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
